### ISSUE TITLE
licenseeSecret

### ISSUE THREAD

**Issue by scottie** [Labs64/NetLicensingClient-csharp#1]
licenseeSecret is not implemented in the initial validate ?

**Comment by scottie** [comment]
licenseeSecret must be turned on within products on the website http://netlicensing.io/, then licenseeSecret  is passed to validate as a validationParameters, Sorted out thanks.

**Comment by r-brown** [comment]
Hello Scott,
Yes, _licenseeSecret_ need to be enabled in product at https://go.netlicensing.io/console/v2/content/vendor/product.xhtml
see also https://www.labs64.de/confluence/display/NLICPUB/Licensee+Secret

**Comment by scottie** [comment]
Thanks friend it is now working 100% as intended a great service, consider this issue closed.
