### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by lostmsu** [Labs64/NetLicensingClient-csharp#10]
Would be nice if you had a [nuget](https://www.nuget.org) package.

**Comment by r-brown** [comment]
Create and publish nuget package: https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package

**Comment by wilsonvargas** [comment]
Please check my PR #12 🐱‍💻🎉🎉🙊

**Comment by wilsonvargas** [comment]
Please check my PR #12 Happy Hacktober Fest!!! 🎉🎉🐱‍💻🙊

**Comment by wilsonvargas** [comment]
cc: @r-brown , @kkorotkov

**Comment by r-brown** [comment]
Please refer to these instructions on how to deploy NuGet package via TravisCI https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci

Main goals here would be:
- do not introduce a dependency on specific environments; e.g. hardcoded Win, MAc, Linux path
- establish automated deployment to NuGet repo
- keep clear and understandable structure (e.g. files, folders naming conventions)

**Comment by kapsiR** [comment]
@wilsonvargas Will you fix that or should another one give it a try? 😉

**Comment by r-brown** [comment]
> @wilsonvargas Will you fix that or should another one give it a try? 😉

Hi @kapsiR sure, very appreciate your help here!

**Comment by kapsiR** [comment]
Perfect. I'll submit a PR the next few days (preferably weekend).

**Comment by r-brown** [comment]
NuGet deploy set up:
- action: https://github.com/Labs64/NetLicensingClient-csharp/actions?query=workflow%3A%22NetLicensing+C%23+Client+-+Release%22
- niget package: https://www.nuget.org/packages/NetLicensingClient-csharp/
