### ISSUE TITLE
Does NetLicensing support desktop applications?

### ISSUE THREAD

**Issue by lostmsu** [Labs64/NetLicensingClient-csharp#11]
In the only sample there's, to create a context and authorize, I can only use either basic authentication with my own credentials, or pass the only API key, that has basically the same access.

Now that, obviously, does not work for desktop applications, because that means I would have to ship my API key with the applications, so users would be able to extract it and wreck chaos to my NetLicensing account.

Is there any plan to support NetLicensing for desktop applications?

**Comment by r-brown** [comment]
Hi @lostmsu ,

You are right - NetLicensing [RESTful API](https://www.labs64.de/confluence/x/pwCo) defines two access methods: `Basic Auth` and `API Key`.

[API Key](https://www.labs64.de/confluence/x/-gHk) was introduced exactly for this purpose - allow limited access to the NetLicensing resources in less secure environments; e.g. JavaScript, execution on-site (customer) scripting languages, etc.
Using API Key you can execute following operations only:
- [LicenseeServices.validate()](https://www.labs64.de/confluence/display/NLICPUB/Licensee+Services#LicenseeServices-Validatelicensee)
- [TokenServices.create()](https://www.labs64.de/confluence/display/NLICPUB/Token+Services#TokenServices-Createtoken)
... these operations will not compromise the security of your products.

Therefore, there is no harm to distribute API Key within your desktop applications.
By having _state-of-the-art_ RESTful API and flexible access methods, NetLicensing can be used in very different environments - from desktop applications to IoT devices and online services (incl. API endpoints protection and monetization).

Could you also share which kind of desktop applications you are planning to create? If this will be compiled and packaged .NET application, we'd recommend obfuscating this to make it difficult, to reverse engineer it.

Best, NetLicensing Team

**Comment by r-brown** [comment]
@lostmsu - please let us know if above explanation resolves your doubts respectively NetLicensing security concepts.

**Comment by lostmsu** [comment]
@r-brown , looks like that answers my question. Perhaps you should make sure this can be easily found in documentation.

**Comment by r-brown** [comment]
@lostmsu I'm glad to hear, that this answer resolves your doubts regarding NetLicensing usage!
You are absolutely right - we need to make it clear in the documentation.
Thank you!

----

see also _Improve APIKey documentation_ issue #9
