### ISSUE TITLE
Bad Javadoc URLs

### ISSUE THREAD

**Issue by HappyPathAB** [Labs64/NetLicensingClient-csharp#20]
Throughout the code, there are references to the NetLicensingAPI Javadoc documentation. However, some of these URLs point to http://netlicensing.labs64.com, which isn't working. They should probably be changed to https://go.netlicensing.io.

The paths also need checking. For instance, NetLicensingClient/Entities/Licensee.cs contains the URL
http://netlicensing.labs64.com/javadoc/v2/com/labs64/netlicensing/common/domain/entity/Licensee.html
but the "common" directory seems to have been removed on the netlicensing.io site, so the corresponding URL should be
https://go.netlicensing.io/javadoc/v2/com/labs64/netlicensing/domain/entity/Licensee.html

The following files contain labs64.com URLs:
NetLicensingClient/Entities/BaseEntity.cs
NetLicensingClient/Entities/License.cs
NetLicensingClient/Entities/Licensee.cs
NetLicensingClient/Entities/LicenseTemplate.cs
NetLicensingClient/Entities/netlicensing-context.cs
NetLicensingClient/Entities/PaymentMethod.cs
NetLicensingClient/Entities/Product.cs
NetLicensingClient/Entities/ProductModule.cs
NetLicensingClient/Entities/Token.cs
NetLicensingClient/Entities/Transaction.cs
NetLicensingClient/Entities/ValidationResult.cs
NetLicensingClient/LicenseeService.cs
NetLicensingClient/LicenseService.cs
NetLicensingClient/LicenseTemplateService.cs
NetLicensingClient/NetLicensingClient.xml
NetLicensingClient/PaymentMethodService.cs
NetLicensingClient/ProductModuleService.cs
NetLicensingClient/ProductService.cs
NetLicensingClient/TokenService.cs
NetLicensingClient/TransactionService.cs

**Comment by r-brown** [comment]
Hello @HappyPathAB & thank you for the hint.
The old deprecated docu link have been verified and fixed now.
