### ISSUE TITLE
NuGet package breaks .NET Core project

### ISSUE THREAD

**Issue by HappyPathAB** [Labs64/NetLicensingClient-csharp#23]
If you add NetLicensingClient 2.4.2 to a Windows Forms project targeting .NET Core, the project breaks somewhat. The Visual Studio designer is unable to show properties for any forms, components, controls etc. You can still compile, but you can't design your forms in the project that references NetLicensingClient.

When you add the package reference, you get a warning NU1701 concerning BouncyCastle:

    Package 'BouncyCastle 1.8.6.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

This makes sense since NetLicensingClient is dependent on BouncyCastle and not BouncyCastle.NetCore. However, as noted in the previous issue, if you try to reference NetLicensingClient in a project that targets .NET Framework all hell breaks loose.

**Comment by HappyPathAB** [comment]
There is a workaround, which is to add another Windows Forms project to the solution (which does not reference NetLicensingClient), and edit the forms in that.

You can move the forms back and forth between the two projects, and the behaviour is consistent: the designer works in the project without a NetLicensingClient reference, and doesn't work in the in the one that has it. You don't even need to restart Studio.

**Comment by r-brown** [comment]
Hi @HappyPathAB the latest released version 2.4.3 - https://www.nuget.org/packages/NetLicensingClient-csharp/2.4.3
uses  Portable.BouncyCastle (1.8.6.7) which is fixing NU1701 message.

Would you mind to verify this in your env. please?

**Comment by r-brown** [comment]
this might also fix #22

**Comment by HappyPathAB** [comment]
2.4.3 eliminates the NU1701 warning, however the main problem persists: after adding the NetLicensingClient package the Visual Studio designer no longer shows properties for the GUI controls.

The workaround I mentioned above turns out to be unviable too: after moving a form back and forth between the projects a few times, the same behaviour is exhibited in the "clean" project.

**Comment by r-brown** [comment]
Close and continue with one issue #22
