### ISSUE TITLE
Wiki lists signatures as not implemented

### ISSUE THREAD

**Issue by HappyPathAB** [Labs64/NetLicensingClient-csharp#26]
The [wiki page](https://netlicensing.io/wiki/signing-the-response) states that response signature "is currently only implemented in the Java NetLicensing Client library", but issue #16 is closed and there's a bunch of signature-related code in netlicensing-context.cs. At the same time, issue #25 seems to indicate that it doesn't work if you target .NET Framework.

So what is the status?

If it's implemented, the wiki page should be updated. And if it's only working for .NET Core that should be mentioned as well.

**Comment by r-brown** [comment]
Hello @HappyPathAB indeed XML signature support was added to C# client library with #16 and the [wiki page](https://netlicensing.io/wiki/signing-the-response) will be updated accordingly. Thank you for this note!

**Comment by r-brown** [comment]
btw. _Enable XML Signature tests on Windows #25_ is related to the GitHub Actions tests only, as we are limited in the options there - CI testing for XML signature was not working at the time of issues creation.

**Comment by HappyPathAB** [comment]
Excellent. Thanks! :)
