### ISSUE TITLE
Product module number missing from validation response

### ISSUE THREAD

**Issue by HappyPathAB** [Labs64/NetLicensingClient-csharp#27]
According to the licensing model wiki pages, each validation response should include
- productModuleNumber
- productModuleName
- licensingModel
- valid

... in addition to any model-specific attributes.
However, productModuleNumber is missing from the response. The other three are there, but the module identity is not.

**Comment by r-brown** [comment]
Hello @HappyPathAB 

Any specific [licensing model](https://netlicensing.io/wiki/licensing-models) you using?

---

This is our test b:

```
curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: application/xml' --header 'Authorization: Basic ZGVtbzpkZW1v' 'https://go.netlicensing.io/core/v2/rest/licensee/ID4Y34ANW-DEMO/validate'
```

**response** (containing all expected fields)
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:netlicensing xmlns="http://www.w3.org/2000/09/xmldsig#" xmlns:ns2="http://netlicensing.labs64.com/schema/context" ttl="2020-10-10T18:38:49.911Z">
  <ns2:infos/>
  <ns2:items>
    <ns2:item type="ProductModuleValidation">
      <ns2:property name="productModuleNumber">M78EH6IKB-DEMO</ns2:property>
      <ns2:property name="valid">false</ns2:property>
      <ns2:property name="productModuleName">Module using "Subscription" licensing model</ns2:property>
      <ns2:property name="licensingModel">Subscription</ns2:property>
    </ns2:item>
  </ns2:items>
</ns2:netlicensing>
```

**Comment by HappyPathAB** [comment]
I have a product which auto-creates licensees, and a Pay-per-Use module which is configured as Default (and also Hide in Shop). There are two other modules, but they are inactive.

When I issue the validation request to create the licensee, the response contains the expected module name but not the number.

When I then issue a normal validation request with the newly created licensee, I get the same: name, but no number.

**Comment by HappyPathAB** [comment]
Sorry, I was looking in the wrong place. My bad. Found it now.
