### ISSUE TITLE
Validation request parameter numbering

### ISSUE THREAD

**Issue by HappyPathAB** [Labs64/NetLicensingClient-csharp#28]
The wiki page for [Licensee Services](https://netlicensing.io/wiki/licensee-services#validate-licensee) states that model-specific validation parameters must be passed with a number suffixed to the parameter name, so that parameters belonging to different modules passed in the same request can be separated. This doesn't work as documented.

I have a PayPerUse module. If I issue a validation request with only that module in the request, and parameters created using `ValidationParameters.put(moduleID, "reserveQuantity0", "1")` (in order to reduce the remaining quantity by one), it doesn't work.
But if I create the parameter with `put(moduleID, "reserveQuantity", "1")` it does work.

On the Javadoc page for [ValidationParameters](https://go.netlicensing.io/javadoc/v2/com/labs64/netlicensing/domain/vo/ValidationParameters.html), `put()` is undocumented. It is also uncommented in the C# source.

So is it the case that `ValidationParameters.put()` handles the numbering and I should always use the parameter name without numbers?
Or must parameters be numbered only if there is more than one module in the validation request? (There is no mention of that on the Licensee Services page).
Or is it that numbered parameters are not supported for PayPerUse modules (or even just for pre-payment)? Again, there is no mention of any different parameter numbering rules for this licensing model.

**Comment by r-brown** [comment]
In the case of multiple product modules validation, required attributes indexes will be added while using client libraries.

C# source code for the reference: https://github.com/Labs64/NetLicensingClient-csharp/blob/master/NetLicensingClient/LicenseeService.cs#L122

While using another toolset, such as CLI, Postman, custom implementation, etc. - indexes need to be added manually.

**Comment by r-brown** [comment]
@HappyPathAB thank you for this hint - we'll update the documentation (source code) accordingly.

**Comment by r-brown** [comment]
All NetLicensing [client libraries](https://github.com/Labs64/NetLicensing-Community#open-source-netlicensing-repositories) updated accordingly.

JavaDoc is part of the  [Labs64/NetLicensingClient-java ](https://github.com/Labs64/NetLicensingClient-java) and will be deployed with the next NetLicensing core release.
