### ISSUE TITLE
PayPerUse validation incorrect

### ISSUE THREAD

**Issue by HappyPathAB** [Labs64/NetLicensingClient-csharp#29]
According to the wiki page for the [PayPerUse](https://netlicensing.io/wiki/pay-per-use) licensing model, a validation response will contain `valid=true` _if the sum of `quantity` of all active licenses (given credits) is **bigger than** the sum of `usedQuantity` of these licenses (used credits)._

In fact, `valid=true` is also returned (alongside `remainingQuantity=0`) if the numbers are equal.

`valid=false` is only returned if (in pre-payment mode) you issue a validation with `reserveQuantity=N` and N is greater than the number of remaining credits.
(Note: I have only tried issuing calls with `reserveQuantity=1`, and only get `valid=false` if there are no credits remaining. I don't know for sure what would happen if there were 10 credits remaining and you asked for 11.)

So if the current behaviour is intended, the documentation needs to be corrected.
But to say that a PayPerUse license is valid when there are no uses left seems a little strange to me.

**Comment by r-brown** [comment]
This issue moved to the NetLicensing Community Support repository - https://github.com/Labs64/NetLicensing-Community/issues/3

**Comment by r-brown** [comment]
Hello @HappyPathAB 
we verified this issue at https://github.com/Labs64/NetLicensing-Community/issues/3#issuecomment-716743260 and confirm the system behaviour as specified and [documented](https://netlicensing.io/wiki/pay-per-use#validation).
