### ISSUE TITLE
Not able to see expiry date on subscriptions at NetLicensing C# client

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-csharp#3]

**Comment by yushkevich** [comment]
Need more information about the issue. The issue does not recur.

This is an example of the code that I use: 
https://github.com/Labs64/NetLicensingClient-csharp/blob/master/NetLicensingClient-demo/NetLicensingClient-demo.cs#L259

**Comment by r-brown** [comment]
Please provide output, with the `expiry date` output in the response

**Comment by yushkevich** [comment]
> Added product:
> Product[number=P001demo, active=True, version=, licenseeAutoCreate=false, inUse=false]
> 
> Added product module:
> ProductModule[number=M001demo, active=True, productNumber=P001demo, name=Demo product module, licensingModel=Subscription, inUse=false]
> 
> Adding license template:
> LicenseTemplate[number=E001demo, active=, name=Demo Evaluation Period, productModuleNumber=, licenseType=TimeVolume, price=12.50, currency=EUR, automatic=False, hidden=False, hideLicenses=, timeVolume=1000]
> 
> Added license template:
> LicenseTemplate[number=E001demo, active=True, name=Demo Evaluation Period, productModuleNumber=M001demo, licenseType=TIMEVOLUME, price=12.50, currency=EUR, automatic=False, hidden=False, hideLicenses=False, productModuleName=Demo product module, inUse=false, timeVolume=1000]
> 
> Added licensee:
> Licensee[number=I001demo, active=True, productNumber=P001demo, inUse=false]
> 
> Added license:
> License[number=L001demoTV, active=True, licenseeNumber=I001demo, licenseTemplateNumber=E001demo, name=Demo Evaluation Period, price=12.50, currency=EUR, hidden=false, timeVolume=1000, startDate=2017-05-03T17:14:18.846Z]
> 
> Created APIKey:
> Token[number=ec39cfbd-a163-465e-b187-473c1e451b4d, active=True, tokenType=APIKEY, vendorNumber=VKW4GEE9G]
> 
> Got the following shop token:
> Token[number=f4dda2a1-84b4-42fe-bbcf-d0b0d30f617e, active=True, expirationTime=2017-05-03T17:44:19.313Z, tokenType=SHOP, shopURL=https://go.netlicensing.io/shop/v2/?shoptoken=f4dda2a1-84b4-42fe-bbcf-d0b0d30f617e, cancelURL=http://netlicensing.io/#cancel, successURL=http://netlicensing.io/#success, successURLTitle=Return to netlicensing.io, cancelURLTitle=Cancel and return to netlicensing.io, licenseeNumber=I001demo, vendorNumber=VKW4GEE9G]
> 
> Validation result for created licensee:
> ProductModuleValidation[ProductModule<M001demo>{valid=true, expires=2020-01-28T17:14:18.846Z, productModuleName=Demo product module, licensingModel=Subscription}]
> 
> Validation repeated with APIKey:
> ProductModuleValidation[ProductModule<M001demo>{valid=true, expires=2020-01-28T17:14:18.846Z, productModuleName=Demo product module, licensingModel=Subscription}]
> 
> All done.

**Comment by r-brown** [comment]
Validation repeated with APIKey:
ProductModuleValidation[ProductModule{valid=true, **expires=2020-01-28T17:14:18.846Z**, productModuleName=Demo product module, licensingModel=Subscription}]
