### ISSUE TITLE
Filter on "list" operation don't seem to work

### ISSUE THREAD

**Issue by werewolf7160** [Labs64/NetLicensingClient-csharp#30]
Hi everyone,
I have try to get all active license based on a licensee number, but i don't seem to reach any data that respect my filter.
I didn't find information about filter in the wiki ([https://netlicensing.io/wiki/license-services#licenses-list](https://netlicensing.io/wiki/license-services#licenses-list)) or in the Api playground ( [https://netlicensing.io/NetLicensing-API/#/](https://netlicensing.io/NetLicensing-API/#/)).

I have tried some syntax but no result. here what I have tested : 

- LicenseService.list(context, licensee.number)
- LicenseService.list(context,"\"licenseeNumber\": \"*licenseeNumber*\"" )
- LicenseService.list(context, "&licenseeNumber=*licenseeNumber*\"");

I have tried the same with "active" or with a parameter of the license (requestid) but no change.

I could filter all the license after received them but in case of the number of license receive in the json exceed a limit that could be problematic

Did I miss something in my implementation or in the wiki ?

**Comment by r-brown** [comment]
Current NetLicensing API doesn't support request filters.
This is planned feature: _**NLQL** - **N**et**L**icensing **Q**uery **L**anguage_

Currently, there is a not-documented feature - `filter` available, which allows you to apply an additional filter to the [list()](https://netlicensing.io/wiki/license-services#licenses-list) operations, e.g.

**... filter licenses list by licenseeNumber**
`/license?filter=page=0;items=100;licenseeNumber=<VALUE>`

**... filter licenses list by licenseTemplateNumber**
`/license?filter=page=0;items=100;licenseTemplateNumber=<VALUE>`

#### Sample (demo:demo account)

**... filter licenses list by licenseeNumber**
```
curl -X GET --header 'Accept: application/xml' --header 'Authorization: Basic ZGVtbzpkZW1v' 'https://go.netlicensing.io/core/v2/rest/license?requestId=VDEMO_1612519007659_124&filter=page=0;items=100;licenseeNumber=CUST-CAD-01' | xmllint --format -
```

---

**Please note:** this feature is not a part of the official [NetLicensing RESTful API](https://netlicensing.io/wiki/services) and will be replaced by _NLQL_.
