### ISSUE TITLE
NetLicensing Blazor Integration

### ISSUE THREAD

**Issue by mikeslab** [Labs64/NetLicensingClient-csharp#33]
Hi Guys,

I VERY new to Blazor and I was wondering if you could please point me in the correct direction on integrating NetLicensing into a Blazor Application?
This Application has a login per Organization. The Application has Modules. Each Organization will have a license per Module.
What is the correct way of doing it and integrating it into the Blazor Application? I have no idea where to start.

Thanks in advance!

**Comment by r-brown** [comment]
Hello @mikeslab ,

I assume you are referring to the Microsoft product [Blazor](https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor).
This framework is backed by C#, so you can use [NetLicensing Client for C#](https://netlicensing.io/wiki/client-libraries) to interface with NetLicensing RESTful services.

On the NetLicensing side you'd need to:
- Configure the product using for instance, [Multi-Feature licensing model](https://netlicensing.io/wiki/multi-feature)
  - this will allow you to enable and disable modules per organization
- Every organization will be represented in the NetLicensing as a customer
- NetLicensing validation request will need to be sent upon organization login
- The result of the validation will be forcing features enable or disable accordingly to the customer's entitlements

Hope that helps you!
