### ISSUE TITLE
Extend demo by LICENSEE_SECRET

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-csharp#4]
Demo [class](https://github.com/Labs64/NetLicensingClient-csharp/blob/master/NetLicensingClient-demo/NetLicensingClient-demo.cs#L259) need to be extended by [LICENSEE_SECRET](https://www.labs64.de/confluence/display/NLICPUB/Licensee+Secret); so this can be showcased as well.

**Comment by yushkevich** [comment]
Added in [link](https://github.com/Labs64/NetLicensingClient-csharp/commit/6f7b9fc5944d271db38d26237dbc254f30e13135)
