### ISSUE TITLE
Resolve remaining TODOs

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-csharp#5]
TODOs need to be worked on and resolved, so client library will be up-to-date
e.g.
https://github.com/Labs64/NetLicensingClient-csharp/blob/master/NetLicensingClient/LicenseeService.cs#L135

**Comment by r-brown** [comment]
@yushkevich what about other TODOs?
see also https://github.com/Labs64/NetLicensingClient-csharp/search?utf8=%E2%9C%93&q=TODO&type=

**Comment by v-rudkovskiy** [comment]
Done in [Labs64/NetLicensingClient-csharp@d7b41aa](https://github.com/Labs64/NetLicensingClient-csharp/commit/d7b41aa8c81480cb16e3700f88db7fee1b9828ca)

**Comment by r-brown** [comment]
@v-rudkovskiy - verify all TODOs - https://github.com/Labs64/NetLicensingClient-csharp/search?utf8=%E2%9C%93&q=TODO&type=

After completion assign for review to @yushkevich

**Comment by v-rudkovskiy** [comment]
Resolved last one [TODO ](https://github.com/Labs64/NetLicensingClient-csharp/search?utf8=%E2%9C%93&q=TODO&type=) in [Labs64/NetLicensingClient-csharp@ba10983](https://github.com/Labs64/NetLicensingClient-csharp/commit/ba10983288987174b7e5e4deae2d0d3c9198b359)

@yushkevich Please review issue

**Comment by r-brown** [comment]
@v-rudkovskiy  Deletion of TODOs cannot be considered as fix. What is the reason for deletion?

**Comment by v-rudkovskiy** [comment]
@r-brown I deleted TODO ("replace dummy response with proper error handling") as it was not justified, the current code on C# repeats the code of the Java library.

C#
![screenshot_9](https://user-images.githubusercontent.com/3775910/32041130-b1dcd54e-ba3b-11e7-9296-72c7f2fd663b.png)

Java
![screenshot_10](https://user-images.githubusercontent.com/3775910/32041139-b6b0d296-ba3b-11e7-80b6-cbc120f6cee4.png)

In **TODO, it was said about error handling**, but in the java code, the exception/error is not given, just **return empty value** same as C#.

**Comment by v-rudkovskiy** [comment]
The same situation with other libraries:
PHP
![screenshot_11](https://user-images.githubusercontent.com/3775910/32041316-4c2b2678-ba3c-11e7-855d-2e3c5c50b3e3.png)

Javascript
![screenshot_12](https://user-images.githubusercontent.com/3775910/32041359-70cead74-ba3c-11e7-9454-eaaefe932a65.png)

It would be strange that only C # throws an exception.

**Comment by r-brown** [comment]
Thank you for the clarification
