### ISSUE TITLE
500 status code when try to validate a licensee

### ISSUE THREAD

**Issue by oleksandr-yeremieiev** [Labs64/NetLicensingClient-csharp#6]
When I try to validate a licensee without any additional validate parameters (empty ValidationParameters object), just using Licensee Number I get 500 response.
I think it happened because the request Body is empty and ContentType not equal to "application/x-www-form-urlencoded".

**Comment by oleksandr-yeremieiev** [comment]
Is "Ready" means "Fixed"? I do not see any changes in csharp client code and I'm still getting the 500 response while trying to validate the licensee only by LicenseeNumber via csharp client from this repository.
Some debug info:
File location - [../RestController/NetLicensingAPI.cs](https://github.com/Labs64/NetLicensingClient-csharp/blob/master/NetLicensingClient/RestController/NetLicensingAPI.cs)
Line 109 - "request" contains "ContentType" property that equal to "null" in my case.
`using (HttpWebResponse response = (request as HttpWebRequest).GetResponse() as HttpWebResponse)`
This request produced the next exception:
"The remote server returned an error: (500) Internal Server Error".
I'm sorry, maybe I'm in a hurry, it's my first issue on GitHub. :)

**Comment by kkorotkov** [comment]
Hi, thanks for reporting the issue and for the info provided. Sorry for confusion, "ready" is not the issue status, it doesn't mean the issue is resolved or closed. Will consider renaming this label. We're still working on solution to the issue, please stay tuned on updates in this thread.

**Comment by oleksandr-yeremieiev** [comment]
Thank you for a clarification. Then I will wait for resolving.

**Comment by yushkevich** [comment]
Fixed in [link](https://github.com/Labs64/NetLicensingClient-csharp/commit/eac37b75601febeb1fb740f857d5b874b7bf014f)

**Comment by oleksandr-yeremieiev** [comment]
I can confirm the defect is fixed. Thank you!
