### ISSUE TITLE
Add "ttl" parameter to the "ValidationResult" class

### ISSUE THREAD

**Issue by oleksandr-yeremieiev** [Labs64/NetLicensingClient-csharp#7]
Could you add "ttl" parameter to the ValidationResult class?
You are recommending (in your documentation [LicenseeServices-Validatelicensee](https://www.labs64.de/confluence/display/NLICPUB/Licensee+Services#LicenseeServices-Validatelicensee) ) to use this parameter on client side to avoid additional load on API server, but the result of validation (ValidationResult class) doesn't contain this parameter.
Thank you.

**Comment by yushkevich** [comment]
added in [pre-2.3.8](https://github.com/Labs64/NetLicensingClient-csharp/tree/pre-2.3.8)

**Comment by v-rudkovskiy** [comment]
Merged pre-2.3.8 (Add "ttl" parameter to the "ValidationResult" commit) with master in [Labs64/NetLicensingClient-csharp@83ddde1](https://github.com/Labs64/NetLicensingClient-csharp/commit/83ddde16233e3936eecb79d917c03d5c12466747)

**Comment by v-rudkovskiy** [comment]
@r-brown Please review task

**Comment by r-brown** [comment]
Branch `pre-2.3.8` deleted after successful review.
