### ISSUE TITLE
Improve APIKey documentation

### ISSUE THREAD

**Issue by r-brown** [Labs64/NetLicensingClient-csharp#9]
Add explicite comment on/at (relevant methods and demo samples):
- what is the scope of the APIKey
- what is the access level

**Comment by yushkevich** [comment]
[Improve APIKey documentation](https://github.com/Labs64/NetLicensingClient-csharp/commit/72f2e5bded7b513c1b0d23484da997fed6df2980)

Documentation and comment added and verified.
